env:
  version: 0.2
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  artifact_name: 'bili_live_bot'

name: Package Application with Pyinstaller
on:
  push:
    branches: [ master ] # for test

jobs:
  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: build exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: main
        artifact: ${{ env.artifact_name }}_windows 

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.artifact_name }}
        path: dist

  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: build exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: main
        artifact: ${{ env.artifact_name }}_linux

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ env.artifact_name }}
        path: dist
  
  upload_releases:
    needs: [build_windows, build_linux]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
      id: download
      with:
        name: ${{ env.artifact_name }}

    - name: Delete tag and release
      id: delete-tag-release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: ${{ env.version }}
        delete_release: true

    - name: zip the directory
      run: |
        [ -d ${{steps.download.outputs.download-path}} ] && ls -la ${{ steps.download.outputs.download-path }}
        cd ${{steps.download.outputs.download-path}}
        zip -r ${{ env.artifact_name }}.zip .
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ github.repository }}-${{ env.version }}
        body: |
          .zip 內有 window 和 linux 的點擊運行程序
          如欲無需 python 環境，可以下載 zip 直接打開程序運行
        draft: false
        prerelease: false

    - name: Upload Release
      id: upload-release-zip
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./${{ env.artifact_name }}.zip
        asset_name: ${{ env.artifact_name }}.zip
        asset_content_type: application/zip

    