env:
  pyinstaller_version: 4.7
  main: main

name: Test Process
on:
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test build exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: main
        artifact: ${{ env.artifact_name }}